alertmanager:
  persistentVolume: #turns off persistent storage for this non-production learning activity
    enabled: false
server:
  persistentVolume: #turns off persistent storage for this non-production learning activity
    enabled: false